import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as fsp from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";

import {
  TEST_YANK_ENV,
  awaitYankVerdict,
  checkYankedDeps,
  parseLockfileDeps,
  yankAbortMessage,
} from "../src/lib/yank-check.js";

const LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "arrayref"
version = "0.3.9"

[[package]]
name = "serde"
version = "1.0.229"
`;

async function writeLock(body = LOCK): Promise<string> {
  const dir = await fsp.mkdtemp(path.join(os.tmpdir(), "yank-check-"));
  const p = path.join(dir, "Cargo.lock");
  await fsp.writeFile(p, body);
  return p;
}

describe("yanked dependency detection (#476)", () => {
  it("parses name/version pairs out of a lockfile", async () => {
    const deps = parseLockfileDeps(LOCK);
    assert.deepEqual(deps, [
      { name: "arrayref", version: "0.3.9" },
      { name: "serde", version: "1.0.229" },
    ]);
  });

  it("flags a dependency named by the test seam", async () => {
    const verdict = await checkYankedDeps({
      lockfilePath: await writeLock(),
      env: { [TEST_YANK_ENV]: "arrayref" },
    });

    assert.equal(verdict.status, "yanked");
    assert.deepEqual(verdict.yanked, [{ name: "arrayref", version: "0.3.9" }]);
  });

  it("reports clean when the seam names a crate the lockfile does not contain", async () => {
    const verdict = await checkYankedDeps({
      lockfilePath: await writeLock(),
      env: { [TEST_YANK_ENV]: "not-a-dependency-here" },
    });

    assert.equal(verdict.status, "clean");
    assert.deepEqual(verdict.yanked, []);
  });

  it("reports clean when the registry finds nothing yanked", async () => {
    const verdict = await checkYankedDeps({
      lockfilePath: await writeLock(),
      env: {},
      lookupYanked: async () => [],
    });

    assert.equal(verdict.status, "clean");
  });

  it("reports not-checked — never clean — when the registry is unreachable", async () => {
    const verdict = await checkYankedDeps({
      lockfilePath: await writeLock(),
      env: {},
      lookupYanked: async () => {
        throw new Error("ENOTFOUND crates.io");
      },
    });

    assert.equal(verdict.status, "not-checked", "an unreachable registry must never read as clean");
    assert.match(verdict.reason ?? "", /unreachable/);
  });

  it("reports not-checked when the lockfile cannot be read", async () => {
    const verdict = await checkYankedDeps({
      lockfilePath: path.join(os.tmpdir(), "definitely-absent", "Cargo.lock"),
      env: { [TEST_YANK_ENV]: "arrayref" },
    });

    assert.equal(verdict.status, "not-checked");
  });

  it("does not consult the registry when no lookup is configured", async () => {
    const verdict = await checkYankedDeps({ lockfilePath: await writeLock(), env: {} });
    assert.equal(verdict.status, "not-checked");
    assert.match(verdict.reason ?? "", /no registry lookup/);
  });

  it("joins a slow check instead of letting the build go green underneath it", async () => {
    const slow = new Promise<Awaited<ReturnType<typeof checkYankedDeps>>>((resolve) =>
      setTimeout(() => resolve({ status: "yanked", yanked: [{ name: "arrayref", version: "0.3.9" }] }), 25),
    );

    const verdict = await awaitYankVerdict(slow, 5_000);

    assert.equal(verdict.status, "yanked", "the join must wait for the real answer");
  });

  it("treats join timeout as not-checked, never as an all-clear", async () => {
    // Resolves eventually rather than never: a truly pending promise keeps the
    // subtest alive and node:test cancels it. What is under test is that the
    // join returns its timeout verdict WITHOUT waiting for this.
    let settle: (v: Awaited<ReturnType<typeof checkYankedDeps>>) => void = () => {};
    const slower = new Promise<Awaited<ReturnType<typeof checkYankedDeps>>>((resolve) => {
      settle = resolve;
    });

    const verdict = await awaitYankVerdict(slower, 20);
    settle({ status: "clean", yanked: [] });

    assert.equal(verdict.status, "not-checked", "slow is not evidence that nothing is yanked");
    assert.match(verdict.reason ?? "", /did not finish/);
  });

  it("names crate, version and the poisoned key in the abort message", () => {
    const msg = yankAbortMessage(
      { status: "yanked", yanked: [{ name: "arrayref", version: "0.3.9" }] },
      "cook-base-v2-linux-x64",
    );

    assert.match(msg, /arrayref@0\.3\.9/);
    assert.match(msg, /cook-base-v2-linux-x64/);
    assert.match(msg, /deleted/, "must say the key is being removed, since that is the repair");
  });
});
